apiVersion: v1
kind: Service
metadata:
<<<<<<< HEAD
  name: content-engine # <srv-name>.<srv-namesapce>.svc.cluster.local
spec:
  selector:
    app: web
  # type: LoadBalancer # -> Node Balancer
  # type: NodePort # public ip -> attached to the vm
  type: ClusterIP # private service
  ports:
    - name: http
      protocol: TCP
      port: 80 # mydomain.com -> mydomain.com:80
      targetPort: 8080
=======
  name: content-engine
spec:
  selector:
    app: web
  type: LoadBalancer
  ports: 
      -name: http
      protocol: TCP
      port: 80
      targetPort: 8080
>>>>>>> 7aaa06d17b82687db3714004d4251da1285ce34f
