# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: content-engine-configmap
# data:
#   WELCOME_MSG: "Welcome to content engine!"

---

apiVersion: v1
kind: Pod
metadata:
  name: content-engine-pod
  labels:
    app: web
spec:
  containers:
  - name: my-container
    image: sahilkp/content-storgae:latest
    env:
      -name: PORT
      value: "8080"
      -name: WELCOME_MSG
      valueFrom:
        name: content-engine-configmap
        key: WELCOME_MSG
      
    ports:
        -containerPort: 8080