# Generated by Django 5.2.13 on 2026-04-12 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userfile",
            name="size",
            field=models.BigIntegerField(default=0),
        ),
    ]
